Fix for missing socket
    $ mocha

    fs.js:695
      return binding.stat(pathModule._makeLong(path));
                     ^
    Error: ENOENT, no such file or directory '/var/run/docker.sock'
        at Object.fs.statSync (fs.js:695:18)
        at Object.<anonymous> (/Users/jacob/Sites/dockerode/test/spec_helper.js:10:17)